### ISSUE TITLE
Appendix's routine links don't work on live website

### ISSUE THREAD

**Issue by SolidKalium** [LLNL/HPC-Tutorials#3]
Error:
If you go to these two pages, only the first one will let you follow the links to routine-specific info.
https://github.com/LLNL/HPC-Tutorials/blob/main/mpi/appendix_a.md
https://hpc-tutorials.llnl.gov/mpi/appendix_a/

Cause:
The links are relative to the current directory, but because the live server serves appendix_a.md as a directory in the url, the links end up with a bonus `/appendix_a/` in the path, which results in a 404.

Example:
Github links correctly: https://github.com/LLNL/HPC-Tutorials/blob/main/mpi/MPI_appendix/MPI_Bcast.txt
Live site links to this 404: https://hpc-tutorials.llnl.gov/mpi/appendix_a/MPI_appendix/MPI_Bcast.txt
Live site has the page here: https://hpc-tutorials.llnl.gov/mpi/MPI_appendix/MPI_Bcast.txt

**Comment by xorJane** [comment]
Thanks so much for pointing this out @SolidKalium! I just fixed this so that the links from https://hpc-tutorials.llnl.gov/mpi/appendix_a/ are working. It seems like specifying relative links works in markdown but wasn't working (at least the way I did it) in html (which I used to make the Appendix's table of links). 

I'll close this by default, but let me know if anything else still seems amiss. :)
